"""Add attributes to product

Revision ID: 4816d3b77731
Revises: 09f6fd6cab0f
Create Date: 2024-08-25 16:43:03.317054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4816d3b77731'
down_revision: Union[str, None] = '09f6fd6cab0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'product',
        sa.Column(
            'attributes',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'attributes')
    # ### end Alembic commands ###
