"""Update on delete in product

Revision ID: f51205cdff6e
Revises: 4816d3b77731
Create Date: 2024-08-26 05:20:37.292567

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51205cdff6e'
down_revision: Union[str, None] = '4816d3b77731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'product',
        'category_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(
        None,
        'product',
        'category',
        ['category_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(
        'product_category_id_fkey',
        'product',
        'category',
        ['category_id'],
        ['id'],
    )
    op.alter_column(
        'product',
        'category_id',
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
